"""add reel scenes

Revision ID: 17cd01216522
Revises: 73741477be60
Create Date: 2026-08-26 12:27:51.330058

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '17cd01216522'
down_revision: Union[str, Sequence[str], None] = '73741477be60'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reel_scenes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('reel_id', sa.Integer(), nullable=False),
    sa.Column('clip_number', sa.Integer(), nullable=False),
    sa.Column('presenter_action', sa.Text(), nullable=False),
    sa.Column('background_action', sa.Text(), nullable=False),
    sa.Column('camera_action', sa.Text(), nullable=False),
    sa.Column('prompt', sa.Text(), nullable=True),
    sa.Column('video_path', sa.String(length=500), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['reel_id'], ['reel_contents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reel_scenes')
    # ### end Alembic commands ###
