"""add category and topic to content items

Revision ID: 51160fd3530d
Revises: 52e2528305fc
Create Date: 2026-08-23 11:29:19.937450

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '51160fd3530d'
down_revision: Union[str, Sequence[str], None] = '52e2528305fc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('content_items', sa.Column('category', sa.String(length=50), nullable=True))
    op.add_column('content_items', sa.Column('topic', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('content_items', 'topic')
    op.drop_column('content_items', 'category')
    # ### end Alembic commands ###
