"""add public url to media assets

Revision ID: 52e2528305fc
Revises: 9e2b0eaeebc4
Create Date: 2026-08-22 17:50:58.622434

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '52e2528305fc'
down_revision: Union[str, Sequence[str], None] = '9e2b0eaeebc4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('media_assets', sa.Column('public_url', sa.String(length=1000), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('media_assets', 'public_url')
    # ### end Alembic commands ###
