"""add scene start frame url

Revision ID: 976ccca570c5
Revises: 17cd01216522
Create Date: 2026-08-26 12:53:53.891792

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '976ccca570c5'
down_revision: Union[str, Sequence[str], None] = '17cd01216522'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reel_scenes', sa.Column('start_frame_url', sa.String(length=1000), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reel_scenes', 'start_frame_url')
    # ### end Alembic commands ###
