"""add job id to scheduled posts

Revision ID: 9e2b0eaeebc4
Revises: 6e5710b40832
Create Date: 2026-08-20 12:15:26.832887

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9e2b0eaeebc4'
down_revision: Union[str, Sequence[str], None] = '6e5710b40832'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scheduled_posts', sa.Column('job_id', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('scheduled_posts', 'job_id')
    # ### end Alembic commands ###
