"""add scene end frame url

Revision ID: a80cd65c168b
Revises: 976ccca570c5
Create Date: 2026-08-26 13:07:38.640026

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a80cd65c168b'
down_revision: Union[str, Sequence[str], None] = '976ccca570c5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reel_scenes', sa.Column('end_frame_url', sa.String(length=1000), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reel_scenes', 'end_frame_url')
    # ### end Alembic commands ###
