"""add reel job tracking

Revision ID: b2f9134c5fb6
Revises: a80cd65c168b
Create Date: 2026-08-31 14:36:27.161338

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b2f9134c5fb6'
down_revision: Union[str, Sequence[str], None] = 'a80cd65c168b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scheduled_posts', sa.Column('reel_job_id', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('scheduled_posts', 'reel_job_id')
    # ### end Alembic commands ###
