"""remove reel scenes

Revision ID: cb9c406ec5fd
Revises: b2f9134c5fb6
Create Date: 2026-09-08 13:27:49.239598

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'cb9c406ec5fd'
down_revision: Union[str, Sequence[str], None] = 'b2f9134c5fb6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reel_scenes')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reel_scenes',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('reel_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('clip_number', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('presenter_action', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('background_action', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('camera_action', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('prompt', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('video_path', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=30), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('start_frame_url', sa.VARCHAR(length=1000), autoincrement=False, nullable=True),
    sa.Column('end_frame_url', sa.VARCHAR(length=1000), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['reel_id'], ['reel_contents.id'], name=op.f('reel_scenes_reel_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('reel_scenes_pkey'))
    )
    # ### end Alembic commands ###
